name: Linter Flake8

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Python install
      uses: actions/setup-python@v2
      with:
          python-version: 3.9
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.2
    - name: Poetry install
      run: poetry install
        
    - name: Run my linter
      run: make lint
