name: Python package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.2
        
    - name: Run my linter
      run: poetry run flake8 brain_games
