name: Python package

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Poetry install
      run: |
        poetry install
        
    - name: Run my linter
      run: |
        make lint
