name: Test my project

on: push

jobs:
  test-job:
    name: Lint code base

    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.4
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run my linter
        run: poetry run flake8 brain_games
